In [1]:
%matplotlib inline
import pandas as pd
import uproot
import matplotlib.pyplot as plt
import numpy as np
import healpy as hp

In [2]:
datafile = uproot.open("/mnt/Storage/fmanzali/FlatComplete/eplus_hits_dn_0.root")
datafile.keys()

[b'lpmt_hits;187',
 b'lpmt_hits;186',
 b'spmt_hits;5',
 b'spmt_hits;4',
 b'true_info;1',
 b'lpmt_pos;1',
 b'spmt_pos;1']

In [3]:
trueINFO = datafile["true_info"]
trueINFO_pd = trueINFO.pandas.df()
trueINFO_pd

       evtID         E             x             y             z             R
entry
0          0  4.747791   8290.779297  11995.618164    911.742859  14610.377930
1          1  3.919721  11397.631836   5407.449707  -7409.082031  14630.140625
2          2  6.823932  14063.337891  -3812.854004    246.652802  14573.131836
3          3  3.765940  -2377.930664 -16317.702148   3315.590332  16820.080078
4          4  3.217473  -8617.117188    868.511597   9730.986328  13026.938477
...      ...       ...           ...           ...           ...           ...
99995  99995  2.863076 -13419.921875  -9861.937500   -440.423920  16659.714844
99996  99996  4.219520  -8444.309570  -3457.845703  -8388.169922  12394.533203
99997  99997  7.254750 -15518.010742   7718.442383  -1728.948975  17417.585938
99998  99998  1.622887   2102.758789   1193.905884 -12095.817383  12335.145508
99999  99999  3.986709  -8331.297852  -8650.178711   9218.859375  15140.127930

[100000 rows x 6 columns]

In [4]:
def filt_pos(frame):

    data = []
    for i in range(0,len(frame)):
        if frame.loc[i, 'R'] < 16500 and frame.loc[i, 'R'] > 15500:
                data.append({'evtID': frame.loc[i, 'evtID'], 'E': frame.loc[i, 'E'],
                           'x': frame.loc[i, 'x'],
                           'y': frame.loc[i, 'y'],
                           'z': frame.loc[i, 'z'],
                           'R': frame.loc[i, 'R']})
            
    trueINFO_pd_0 = pd.DataFrame(data)
    return trueINFO_pd_0

In [5]:
infoR = filt_pos(trueINFO_pd)
infoR

       evtID         E             x             y             z             R
0          6  7.886344   1658.723022 -12691.513672  -9842.650391  16146.320312
1          9  6.786881 -12249.327148  -8324.336914  -5930.173828  15953.292969
2         10  4.763122   3361.870117  11073.585938 -10755.718750  15799.112305
3         13  3.580564  -1830.479492  10861.013672  11719.223633  16082.675781
4         22  7.298966   6935.369141  13709.882812   5014.570801  16161.873047
...      ...       ...           ...           ...           ...           ...
13837  99967  5.350537  14676.946289  -3960.216553  -6015.730469  16348.855469
13838  99968  4.773934    509.530212    -82.437874 -16318.811523  16326.972656
13839  99969  8.014432 -13872.530273  -7181.908691   5250.836914  16480.236328
13840  99983  7.022244 -10696.417969  11144.188477   5766.138184  16488.015625
13841  99988  8.866767  14522.831055   1058.682007  -7217.714355  16252.041016

[13842 rows x 6 columns]

In [6]:
largePMT = datafile["lpmt_hits"]

In [7]:
i=0
frame = largePMT.arrays(outputtype=pd.DataFrame, entrystart=i*10000, entrystop=(i+1)*10000)
lin = np.linspace(i*10000, (i+1)*10000-1, 10000, dtype=np.int)
frame.insert(0, 'evID', lin)
largeR = frame.loc[frame['evID'].isin(infoR['evtID'].values)]
largeR

,evID,nHits,pmtID,hitTime,isDN
entry,,,,,
6,6,13380,"[11617, 8267, 2635, 9633, 12267, 11032, 12268,...","[30.869078, 138.48528, 233.76862, 133.96402, 3...","[False, False, False, False, False, False, Fal..."
9,9,12134,"[15881, 13102, 5199, 14657, 11455, 15427, 4998...","[27.654234, 23.676601, 96.554695, 29.353798, 7...","[False, False, False, False, False, False, Fal..."
10,10,8559,"[3610, 11984, 11551, 10067, 10089, 992, 8730, ...","[246.58301, 36.132336, 62.82003, 87.60815, 77....","[False, False, False, False, False, False, Fal..."
13,13,6847,"[2054, 4945, 17077, 10479, 17353, 2501, 14016,...","[24.744009, 127.5423, 140.71101, 167.36739, 11...","[False, False, False, False, False, False, Fal..."
22,22,12466,"[6513, 16486, 6559, 6561, 1929, 17580, 1056, 3...","[353.22983, 128.0007, 21.69416, 70.76658, 150....","[False, False, False, False, False, False, Fal..."
...,...,...,...,...,...
9972,9972,10972,"[16690, 628, 10442, 17541, 6396, 9286, 15465, ...","[42.495308, 193.48045, 81.32712, 86.85248, 131...","[False, False, False, False, False, False, Fal..."
9975,9975,15531,"[9571, 16916, 15631, 17337, 16918, 8343, 14393...","[105.79387, 31.113142, 21.827765, 78.00931, 65...","[False, False, False, False, False, False, Fal..."
9979,9979,4970,"[1966, 5880, 5219, 15908, 10822, 12295, 12612,...","[174.60324, 148.14835, 260.2863, 225.11703, 25...","[False, False, False, False, False, False, Fal..."
9986,9986,12600,"[1538, 622, 54, 5267, 1682, 9795, 960, 586, 25...","[168.7881, 160.44331, 46.059544, 162.62721, 15...","[False, False, False, False, False, False, Fal..."
9996,9996,8077,"[15631, 8386, 15171, 13597, 5993, 14364, 7636,...","[75.39949, 191.14517, 37.53811, 72.83829, 117....","[False, False, False, False, False, False, Fal..."

In [27]:
largeR.loc[6]['isDN']

array([False, False, False, ...,  True,  True,  True])

In [7]:
def take_right(file, i):
    
    #data = []
    #for i in range(50):
        frame = pd.DataFrame()
        lin = []
        frame = file.arrays(outputtype=pd.DataFrame, entrystart=i*2000, entrystop=(i+1)*2000)
        lin = np.linspace(i*2000, (i+1)*2000-1, 2000, dtype=np.int)
        frame.insert(0, 'evID', lin)
        #for j in range(len(frame)):
            #for ev in infoR.loc[:, 'evtID' ]:
                   # if ev == frame.index[j][0] : 
                   #     for k in range(len(frame.loc[ev])):
                            #data.append({'ev': ev, 
                            #             'nHits': frame.loc[frame['nHits']].loc[k],
                            #             'pmtID': frame.loc[ev, 'pmtID'].loc[k],
                            #             'hitTime': frame.loc[ev, 'hitTime'].loc[k],
                            #             'isDN': frame.loc[ev, 'isDN'].loc[k]})
        new_frame = frame.loc[frame['evID'].isin(infoR['evtID'].values)]
        #data.append(new_frame)
        #new_frame
    #tot = pd.concat(data)   
    return new_frame

In [8]:
largeR = take_right(largePMT)

MemoryError: Unable to allocate array with shape (19872421,) and data type float32

In [67]:
largeR

,evID,nHits,pmtID,hitTime,isDN
entry,,,,,
98001,98001,6158,"[7535, 3722, 5033, 3482, 4294, 5239, 14142, 80...","[146.39749, 631.8993, 69.50502, 772.5648, 92.0...","[False, False, False, False, False, False, Fal..."
98003,98003,4717,"[16171, 7375, 17707, 17711, 14710, 16147, 4864...","[64.10371, 56.72899, 27.923103, 23.103596, 37....","[False, False, False, False, False, False, Fal..."
98008,98008,8727,"[14121, 234, 17738, 14129, 7394, 6971, 8709, 1...","[53.786755, 155.99255, 27.601961, 73.2382, 398...","[False, False, False, False, False, False, Fal..."
98016,98016,4782,"[11951, 5479, 6286, 9458, 17513, 15971, 8047, ...","[87.11315, 64.09103, 74.2562, 174.65068, 79.54...","[False, False, False, False, False, False, Fal..."
98019,98019,14154,"[4888, 15992, 291, 7134, 1686, 2977, 17737, 27...","[244.28123, 198.43338, 34.23184, 139.7444, 64....","[False, False, False, False, False, False, Fal..."
...,...,...,...,...,...
99967,99967,9359,"[9347, 7815, 9556, 6758, 5035, 14543, 14305, 1...","[128.88875, 92.72062, 118.748245, 204.52759, 2...","[False, False, False, False, False, False, Fal..."
99968,99968,7531,"[9529, 11015, 7693, 9077, 8980, 10114, 9001, 1...","[48.60321, 102.225174, 214.35468, 69.90239, 40...","[False, False, False, False, False, False, Fal..."
99969,99969,13159,"[5406, 5635, 7475, 14441, 6029, 5005, 5211, 68...","[79.602005, 188.385, 191.72281, 102.23193, 102...","[False, False, False, False, False, False, Fal..."
99983,99983,11736,"[3669, 6599, 7696, 17124, 2466, 15268, 5986, 1...","[62.758186, 45.90526, 39.400166, 84.08462, 174...","[False, False, False, False, False, False, Fal..."
99988,99988,14743,"[13751, 5753, 8081, 13751, 16546, 15773, 11655...","[28.163313, 243.92693, 194.83519, 48.468094, 1...","[False, False, False, False, False, False, Fal..."

In [94]:
def no_DN (frame):
    data = []

    i = frame.index[0][0]
    a = 0
    for j in range(0,len(frame.loc[i])): 
        if frame.loc[i, 'isDN'].loc[j] == False and frame.loc[i, 'hitTime'].loc[j] < 300:
            a += 1
    for j in range(0,len(frame.loc[i])): 
        if frame.loc[i, 'isDN'].loc[j] == False and frame.loc[i, 'hitTime'].loc[j] < 300:
            data.append({'nHits': a,
                       'pmtID': frame.loc[i, 'pmtID'].loc[j],
                       'hitTime': frame.loc[i, 'hitTime'].loc[j] })
            
    frame_noDN = pd.DataFrame(data)
    return frame_noDN

In [95]:
def normal_ft(ev):
    data = []
    ma = ev.loc[:, 'hitTime'].max()
    mi = ev.loc[:, 'hitTime'].min()
    mami = ma - mi
    for i in range(0, len(ev)):
        a = ev.loc[i, 'nHits']
        b = ev.loc[i, 'pmtID']
        c = (ev.loc[i, 'hitTime'] - mi)/mami
        data.append({'nHits': a, 'pmtID': b, 'hitTime': c})
        
    norm = pd.DataFrame(data)
    return norm

In [ ]:
def ev_mollweide (ev_map):
    # Set the coordinates for the input
    nside = 16
    npix = hp.nside2npix(nside)

    # Coordinates and the density field f
    thetas = PMT_spher_pd.loc[:, 'pmt_theta']
    phis = PMT_spher_pd.loc[:, 'pmt_phi']
    hitTime = ev_map.loc[:, 'hitTime']

    # Go from HEALPix coordinates to indices
    indices = hp.ang2pix(nside, thetas, phis)

    # Initate the map and fill it with the values
    hpxmap = np.zeros(npix, dtype=np.float)
    for i in range(len(ev_map)):
        hpxmap[indices[ev_map.loc[:, 'pmtID'].loc[i]]]  = hitTime.loc[i]
   # for j in range(len(hpxmap)):
   #     if hpxmap[j] == 0:
   #         hpxmap[j] = 1024
        
    # Inspect the map
    hp.mollview(hpxmap) #non mostrare ma salva su file

In [ ]:
def make_image(file):
    
    for i in range(20):
        frame = pd.DataFrame()
        if i == 0:
            frame = file.pandas.df(entrystart=i, entrystop=5000)
        else:
            frame = file.pandas.df(entrystart=i*5001-(i-1), entrystop=(i+1)*5000)
        for j in range(len(frame)):
            for ind in infoR.loc[:, 'evtID' ]:
                    if ind == frame.index[j][0] : 
                        ev = pd.DataFrame()
                        ev = file.pandas.df(entrystart=ind, entrystop=ind+1)
                        ev_noDN = no_DN(ev)
                        ev_norm = normal_ft(ev_noDN)
                        ev_mollweide(ev_norm)